// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Prefer environment variables; fall back to generated defaults if needed
interface EnvWindow extends Window {
  VITE_SUPABASE_URL?: string;
  VITE_SUPABASE_ANON_KEY?: string;
  VITE_SUPABASE_PUBLISHABLE_KEY?: string;
}

const w: EnvWindow | undefined =
  typeof window !== "undefined" ? (window as EnvWindow) : undefined;

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  w?.VITE_SUPABASE_URL ||
  "https://yolpznlxwkmuagxgdywy.supabase.co";

const SUPABASE_ANON_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  w?.VITE_SUPABASE_ANON_KEY ||
  w?.VITE_SUPABASE_PUBLISHABLE_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvbHB6bmx4d2ttdWFneGdkeXd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMjUzNDYsImV4cCI6MjA3MTYwMTM0Nn0.WJ14E7DW_JPt9OeDYGEhEbi9RnQy76Fsj0KcVjwuQiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
